Repository briantist/galactory, pull requests merged in 2022-12, with the labels that each got.

#26 Merge env into prepared session
  changelogs/fragments/25-requests-environment.yml
  galactory/upstream.py
Labels: enhancement

#29 Fix URL generation for scheme and self-referential URLs
  README.md
  changelogs/fragments/27-protocol-urls.yml
  galactory/__init__.py
  galactory/api/__init__.py
  galactory/api/v2/collections.py
  galactory/utilities.py
  tests/unit/utilities/test_collected_collections.py
Labels: bug

#32 Control `Accept` header on upstream proxying, add support for brotli compression
  changelogs/fragments/32-headers-brotli.yml
  galactory/upstream.py
  requirements.txt
  setup.cfg
Labels: bug

#33 Add healthcheck endpoint
  README.md
  changelogs/fragments/30-healthchecks.yml
  galactory/__init__.py
  galactory/health/__init__.py
  galactory/health/v1/__init__.py
  galactory/health/v1/health_checks.py
Labels: enhancement

#34 add href to health check responses
  galactory/api/v2/collections.py
  galactory/health/v1/health_checks.py
Labels: enhancement

#43 fix datetime JSON bug affecting upstream proxying
  changelogs/fragments/42-upstream-proxy-json.yml
  galactory/__init__.py
  galactory/upstream.py
  galactory/utilities.py
Labels: bug

#46 fix upstream rewriting scheme problem
  .github/workflows/test.yml
  Dockerfile
  changelogs/fragments/45-upscheme.yml
  galactory/__init__.py
  galactory/root.py
  galactory/upstream.py
  tests/unit/client/conftest.py
  tests/unit/client/test_api.py
  tests/unit/client/test_health.py
  tests/unit/client/test_root.py
Labels: bug, enhancement

#48 add minimal ProxyFix support
  changelogs/fragments/48-proxyfix.yml
  galactory/__init__.py
Labels: enhancement
